import React from 'react'
import Wrapper from "./Wrapper"
export const metadata = {
  title: "Bidfest -  Notifications",
  description: "Generated by create next app",
};
function Page() {
  return (
    <Wrapper/>
  )
}

export default Page