import React from 'react'
import Wrapper from './Wrapper'
export const metadata = {
    title: "Bidfest - Search for items",
    description: "Generated by create next app",
  };
function Page() {
  return (
    <Wrapper/>
  )
}

export default Page