import React from 'react'
import { FaCheck } from 'react-icons/fa'
export const metadata = {
    title: "Bidfest -  Cookie Policy",
    description: "Generated by create next app",
  };
  
function Page() {
  return (
    <div>
           <>
    <div className='bg-[#635BFF] text-white'>

<h2 className="text-white text-2xl font-bold px-12 pt-5">
Cookie Policy for Bidfirst
</h2>


<h3 className='text-white text-[19px] font-bold px-12 pt-5 mb-4'>
    Last Updated : 16/09/25
</h3>

<p className='text-white text-1xl px-12 w-[92%]'>


At Bidfirst, we use cookies and similar technologies to enhance your experience on our platform. This Cookie Policy explains what cookies are, how we use them, and your choices regarding cookies.

</p>





<h2 className="text-white text-2xl font-bold px-12 pt-5">
1. What Are Cookies?
</h2>

<p className="text-white text-1xl  px-12 pt-2">
Cookies are small text files stored on your device when you visit a website. They help websites function properly, remember user preferences, and collect analytical data to improve services.

</p>










<h2  className="text-white text-2xl font-bold px-12 pt-5">
2. Why We Use Cookies
</h2>
<p className="text-white text-1xl px-12 pt-2">

Bidfirst uses cookies to:
</p>
<ul className='px-12 pt-2 grid gap-1'>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>  Create and manage user accounts      </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Facilitate auctions and process transactions       </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Send confirmations and notifications        </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Respond to inquiries and support requests         </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Improve our services and user experience          </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>Comply with legal obligations           </li>

</ul>
<p className="text-white text-1xl px-12 pt-2">
We may allow third-party service providers to place cookies on your device to assist with analytics, advertising, or social media integrations. These providers are governed by their own privacy policies.

</p>
<h2 className="text-white text-2xl font-bold px-12 pt-5">
3. Types of Cookies We Use
</h2>

<ul className='px-12 pt-2 grid gap-1'>




    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Essential Cookies: Required for core functionality (e.g., logging in, placing bids).     </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Performance & Analytics Cookies: Help us understand how visitors use our site (e.g., Google Analytics).     </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Functionality Cookies: Remember choices you make to improve your experience.     </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Targeting/Advertising Cookies: May be used to show relevant ads or offers (if applicable).       </li>

</ul>




<h2 className="text-white text-2xl font-bold px-12 pt-5">
4. 

Your Cookie Choices

</h2>
<p className="text-white text-1xl px-12 pt-2">
When you first visit *Bidfirst*, you may be prompted to accept or manage cookies. You can:


</p>
<ul className='px-12 pt-2 grid gap-1'>



    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>Accept all cookies. 

     </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Customize your cookie preferences.
       </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Reject non-essential cookies.       </li>


</ul>
<p className="text-white text-1xl px-12 pt-2">
You can also control cookies through your browser settings by clearing or blocking them. Note that disabling certain cookies may affect the functionality of the site.

</p>



<h2 className="text-white text-2xl font-bold px-12 pt-5">
5. Updates to This Policy


</h2>
<p className="text-white text-1xl px-12 pt-2 w-[92%]">

We may update this Cookie Policy from time to time. Any changes will be posted on this page with an updated effective date.


</p>


<h2 className="text-white text-2xl font-bold px-12 pt-5">


7. Contact Us
</h2>
<p className="text-white text-1xl px-12 pt-2">




If you have any questions about this Cookie Policy, please contact us at:
<br/>
Email: support@bidfirst.co.zw  
Address: 20 Hatfield Harare

</p>






 







    </div>
    </>






    </div>
  )
}

export default Page