import React from 'react'
import AuctionWrapper from './AuctionWrapper'
export const metadata = {
    title: "Bidfest -  Onsite Auctions",
    description: "Generated by create next app",
  };
function Page() {
  return (
    <AuctionWrapper/>
  )
}

export default Page