import Image from "next/image";
import MarketingHero from "@/components/marketingHero"
import { headers } from "next/headers";
export const metadata: Metadata = {
  title: "Bidfest -  Trusted platform for smart buyers and serious sellers.",
  description: "Generated by create next app",
};
import type { Metadata } from "next";
export default function Home() {
  return (


    <MarketingHero/>
  );
}
