import React from 'react'
export const metadata = {
    title: "Bidfest -  Contact Us",
    description: "Generated by create next app",
  };
function Page() {
  return (
    <>
       <div   className='bg-[#635BFF] text-white h-[100vh]'>
       <h2 className="text-white text-2xl font-bold px-12 pt-5">
Contact Us
</h2>
<p className='px-12'>
    Have any questions? We'd love to hear from you. <br/>
    <p className='flex gap-2'>
    <span className='cursor-pointer' style={{
        textDecoration:'underline'
    }}>
078 4313 785
    </span>

    <span className='cursor-pointer' style={{
        textDecoration:'underline'
    }}>
support@bidfest.co.zw
    </span>
    </p>
 

</p>
</div>
    </>
 
  )
}

export default Page