import Image from "next/image";
import FAQS from "./faqs"
import { headers } from "next/headers";

export const metadata = {
  title: "Bidfest -  FAQS.",
  description: "Generated by create next app",
};

export default function Page() {
  return (


    <FAQS/>
  );
}