import React from 'react'
import { FaCheck } from 'react-icons/fa'
import Footer from "../../components/Footer"
export const metadata = {
    title: "Bidfest -  Privacy Policy",
    description: "Generated by create next app",
  };
  
function Page() {
  return (
    <>
    <div className='bg-[#635BFF] text-white '>

<h2 className="text-white text-2xl font-bold px-12 pt-5">
Privacy Policy for Bidfirst
</h2>


<h3 className='text-white text-[19px] font-bold px-12 pt-5'>
    Last Updated : 16/09/25
</h3>

<p className='text-white text-1xl px-12 w-[92%]'>
At Bidfirst, your privacy is important to us. This Privacy Policy explains how we collect, use, disclose, and protect your information when you visit our website www.bidfirst.co.zw or use our services.

</p>


<h2 className="text-white text-2xl font-bold px-12 pt-5">
1. Information We Collect
</h2>

<p className="text-white text-1xl  px-12 pt-2">
We may collect the following types of information:
</p>
<p className="text-white text-1xl px-12 pt-2">
a. Personal Information
</p>

<ul className='px-12 pt-2 grid gap-1'>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Name   </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Email address     </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Phone number      </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Billing/shipping address       </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> ID/verification documents (for compliance)      </li>
</ul>


<p className="text-white text-1xl px-12 pt-2">
b. Account & Bidding Activity
</p>

<ul className='px-12 pt-2 grid gap-1'>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>  Username, password     </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Auction participation history      </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Bids placed and items won      </li>

</ul>
<p className="text-white text-1xl px-12 pt-2">
c. Technical Data
</p>

<ul className='px-12 pt-2 grid gap-1'>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> IP address      </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Browser type and version      </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Device information       </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Cookies and usage data        </li>

</ul>


<h2  className="text-white text-2xl font-bold px-12 pt-5">
2. How We Use Your Information
</h2>
<p className="text-white text-1xl px-12 pt-2">
We use the information we collect to:
</p>
<ul className='px-12 pt-2 grid gap-1'>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>  Create and manage user accounts      </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Facilitate auctions and process transactions       </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Send confirmations and notifications        </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Respond to inquiries and support requests         </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Improve our services and user experience          </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>Comply with legal obligations           </li>

</ul>
<h2 className="text-white text-2xl font-bold px-12 pt-5">
3. Sharing of Your Information
</h2>
<p className="text-white text-1xl px-12 pt-2">
We may share your data:
</p>
<ul className='px-12 pt-2 grid gap-1'>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>  Create and manage user accounts      </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Facilitate auctions and process transactions       </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Send confirmations and notifications        </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> With service providers who help us operate our platform (e.g., payment gateways)           </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> With law enforcement or regulators as required by law         </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>With sellers or buyers as needed to complete a transaction           </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>In case of a business transfer (e.g., merger or sale of assets)           </li>

</ul>
<h2 className="text-white text-2xl font-bold px-12 pt-5">
4. Cookies and Tracking Technologies
</h2>
<p className="text-white text-1xl px-12 pt-2">
We use cookies to:
</p>
<ul className='px-12 pt-2 grid gap-1'>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>Remember your preferences  

     </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Analyze website traffic  
       </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Provide a better user experience        </li>


</ul>


<h2 className="text-white text-2xl font-bold px-12 pt-5">

5. Data Security
</h2>
<p className="text-white text-1xl px-12 pt-2 w-[92%]">

We implement reasonable technical and organizational safeguards to protect your personal data. However, no system is 100% secure, and we encourage users to protect their login credentials.

</p>


<h2 className="text-white text-2xl font-bold px-12 pt-5">


6. Your Rights
</h2>
<p className="text-white text-1xl px-12 pt-2">

Depending on your jurisdiction, you may have rights to:


</p>
<ul className='px-12 pt-2 grid gap-1 '>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/>Access, update, or delete your personal data   

     </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Object to or restrict certain data processing 
       </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> Withdraw consent where applicable         </li>
    <li className='flex align-middle items-center gap-2'><FaCheck size={12}/> To exercise any of these rights, contact us at support@bidfirst.co.zw         </li>


</ul>







 






<div className='mb-9'>

</div>
    </div>
 
    </>
  )
}

export default Page