import React from 'react'
import Wrapper from "./Wrapper"
 const metadata = {
    title: "Bidfest - Register For The Bidding To Begin",
    description: "Generated by create next app",
  };
function Page() {
  return (
<Wrapper/>
  )
}

export default Page